### ISSUE TITLE
reduce CSS specificity

### ISSUE THREAD

**Issue by blesh** [Netflix/ember-nf-graph#12]
Example, styling an nf-area:

```css
.my-area > .area {
   fill: blue;
}
```

this should not be a requirement. A simple class or two should be able to override the default behavior.
Example:

```css

.my-area {
  fill: blue
}

/* or */

.my-area .area {
  fill: blue
}
```

The first is ideal, but because of the nested nature of some of these components, some specificity will likely be required, as the `class` is applied to the component container.
