### ISSUE TITLE
nf-graph should not disable user-select/drag for every element within

### ISSUE THREAD

**Issue by jayphelps** [Netflix/ember-nf-graph#84]
Right now everything inside `.nf-graph` is made non-selectable/draggable. This prevents someone from easily copying numbers, labels, etc which I don't think was the intent.
```css
.nf-graph * {
  user-select: none;
  user-drag: none;
}
```
https://github.com/Netflix/ember-nf-graph/blob/d74b0e533449f36aae680d8d19c12d44986ccd7e/styles/scss/components/nf-graph.scss#L16-L24

Instead, we should explicitly opt out things that should be selectable, Things like lines, paths, etc; if this is even necessary?
